//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Pathfinder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.Pathfinder.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey - there is no &apos;Website&apos; directory under the &apos;wwwroot&apos; directory - are you sure = you have set the &apos;wwwroot&apos; correctly in the configuration file.
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------.
        /// </summary>
        public static string _______________ {
            get {
                return ResourceManager.GetString("_______________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Boolean parameter must have value &quot;True&quot; or &quot;False&quot;.
        /// </summary>
        public static string @__Boolean_parameter_must_have_value__True__or__False_ {
            get {
                return ResourceManager.GetString("__Boolean_parameter_must_have_value__True__or__False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is not defined in the parameters template.
        /// </summary>
        public static string _1___Parameter___0___is_not_defined_in_the_parameters_template_ {
            get {
                return ResourceManager.GetString("_1___Parameter___0___is_not_defined_in_the_parameters_template_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}: Placeholder &quot;{0}&quot; is not defined in the parent rendering. Parent rendering has these placeholders: {1}.
        /// </summary>
        public static string _2___Placeholder___0___is_not_defined_in_the_parent_rendering__Parent_rendering_has_these_placeholders___1__ {
            get {
                return ResourceManager.GetString("_2___Placeholder___0___is_not_defined_in_the_parent_rendering__Parent_rendering_h" +
                        "as_these_placeholders___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Component&apos; element expected.
        /// </summary>
        public static string _Component__element_expected {
            get {
                return ResourceManager.GetString("_Component__element_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Field&apos; element must have a &apos;Name&apos; attribute.
        /// </summary>
        public static string _Field__element_must_have_a__Name__attribute {
            get {
                return ResourceManager.GetString("_Field__element_must_have_a__Name__attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Item&apos; element must have a &apos;Template&apos; or &apos;Template.Create&apos; attribute.
        /// </summary>
        public static string _Item__element_must_have_a__Template__or__Template_Create__attribute {
            get {
                return ResourceManager.GetString("_Item__element_must_have_a__Template__or__Template_Create__attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Section&apos; element must have a &apos;Name&apos; attribute.
        /// </summary>
        public static string _Section__element_must_have_a__Name__attribute {
            get {
                return ResourceManager.GetString("_Section__element_must_have_a__Name__attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;version&apos; attribute must have an integer value.
        /// </summary>
        public static string _version__attribute_must_have_an_integer_value {
            get {
                return ResourceManager.GetString("_version__attribute_must_have_an_integer_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not found: .
        /// </summary>
        public static string Action_not_found__ {
            get {
                return ResourceManager.GetString("Action_not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string An_error_occured {
            get {
                return ResourceManager.GetString("An_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly not found in T4 type name in the config setting &apos;generate-code:items&apos;.
        /// </summary>
        public static string Assembly_not_found_in_T4_type_name_in_the_config_setting__generate_code_items_ {
            get {
                return ResourceManager.GetString("Assembly_not_found_in_T4_type_name_in_the_config_setting__generate_code_items_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Template missing.
        /// </summary>
        public static string Base_Template_missing {
            get {
                return ResourceManager.GetString("Base_Template_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply a layout to a template. The template needs a Standard Values..
        /// </summary>
        public static string Cannot_apply_a_layout_to_a_template__The_template_needs_a_Standard_Values_ {
            get {
                return ResourceManager.GetString("Cannot_apply_a_layout_to_a_template__The_template_needs_a_Standard_Values_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run task without a configuration file.
        /// </summary>
        public static string Cannot_run_task_without_a_configuration_file {
            get {
                return ResourceManager.GetString("Cannot_run_task_without_a_configuration_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox field value must be &apos;true&apos; or &apos;false&apos;..
        /// </summary>
        public static string Checkbox_field_value_must_be__true__or__false__ {
            get {
                return ResourceManager.GetString("Checkbox_field_value_must_be__true__or__false__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking project....
        /// </summary>
        public static string Checking___ {
            get {
                return ResourceManager.GetString("Checking___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning output directory....
        /// </summary>
        public static string Cleaning_output_directory___ {
            get {
                return ResourceManager.GetString("Cleaning_output_directory___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition not found: .
        /// </summary>
        public static string Condition_not_found__ {
            get {
                return ResourceManager.GetString("Condition_not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file not found: .
        /// </summary>
        public static string Config_file_not_found__ {
            get {
                return ResourceManager.GetString("Config_file_not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration failed spectacularly.
        /// </summary>
        public static string Configuration_failed_spectacularly {
            get {
                return ResourceManager.GetString("Configuration_failed_spectacularly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration setting &apos;map-website-directory-to-project-directory&apos; is invalid. Are you missing a &apos;=&gt;&apos;?.
        /// </summary>
        public static string ConfigurationSsettingMapWebsiteDirectoryToProjectDirectoryIsInvalid {
            get {
                return ResourceManager.GetString("ConfigurationSsettingMapWebsiteDirectoryToProjectDirectoryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying dependency packages....
        /// </summary>
        public static string Copying_dependencies___ {
            get {
                return ResourceManager.GetString("Copying_dependencies___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string Copying_dependency {
            get {
                return ResourceManager.GetString("Copying_dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying packages to website....
        /// </summary>
        public static string Copying_package_to_website___ {
            get {
                return ResourceManager.GetString("Copying_package_to_website___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying test files to website....
        /// </summary>
        public static string Copying_test_files_to_website___ {
            get {
                return ResourceManager.GetString("Copying_test_files_to_website___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create item.
        /// </summary>
        public static string Could_not_create_item {
            get {
                return ResourceManager.GetString("Could_not_create_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create section item.
        /// </summary>
        public static string Could_not_create_section_item {
            get {
                return ResourceManager.GetString("Could_not_create_section_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create template field.
        /// </summary>
        public static string Could_not_create_template_field {
            get {
                return ResourceManager.GetString("Could_not_create_template_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read exports.xml in dependency package.
        /// </summary>
        public static string Could_not_read_exports_xml_in_dependency_package {
            get {
                return ResourceManager.GetString("Could_not_read_exports_xml_in_dependency_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating packages....
        /// </summary>
        public static string Creating_Nupkg_file___ {
            get {
                return ResourceManager.GetString("Creating_Nupkg_file___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is &apos;core&apos;. Skipping..
        /// </summary>
        public static string Database_is__core___Skipping_ {
            get {
                return ResourceManager.GetString("Database_is__core___Skipping_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not found.
        /// </summary>
        public static string Database_not_found {
            get {
                return ResourceManager.GetString("Database_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasource not found.
        /// </summary>
        public static string Datasource_not_found {
            get {
                return ResourceManager.GetString("Datasource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages directory not found. Skipping.
        /// </summary>
        public static string Dependencies_directory_not_found__Skipping {
            get {
                return ResourceManager.GetString("Dependencies_directory_not_found__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory not found.
        /// </summary>
        public static string Destination_directory_not_found {
            get {
                return ResourceManager.GetString("Destination_directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device element is missing &quot;Name&quot; attribute..
        /// </summary>
        public static string Device_element_is_missing__Name__attribute_ {
            get {
                return ResourceManager.GetString("Device_element_is_missing__Name__attribute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device item not found.
        /// </summary>
        public static string Device_item_not_found {
            get {
                return ResourceManager.GetString("Device_item_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found.
        /// </summary>
        public static string Device_not_found {
            get {
                return ResourceManager.GetString("Device_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices not found in database..
        /// </summary>
        public static string Devices_not_found_in_database_ {
            get {
                return ResourceManager.GetString("Devices_not_found_in_database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is not valid.
        /// </summary>
        public static string Document_is_not_valid {
            get {
                return ResourceManager.GetString("Document_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ducats earned: {0}.
        /// </summary>
        public static string Ducats___0_ {
            get {
                return ResourceManager.GetString("Ducats___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type expected.
        /// </summary>
        public static string Element_type_expected {
            get {
                return ResourceManager.GetString("Element_type_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Name&apos; attribute.
        /// </summary>
        public static string Expected__Name__attribute {
            get {
                return ResourceManager.GetString("Expected__Name__attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new template.
        /// </summary>
        public static string Failed_to_add_new_template {
            get {
                return ResourceManager.GetString("Failed_to_add_new_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change template of the item.
        /// </summary>
        public static string Failed_to_change_template_of_the_item {
            get {
                return ResourceManager.GetString("Failed_to_change_template_of_the_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create item path.
        /// </summary>
        public static string Failed_to_create_item_path {
            get {
                return ResourceManager.GetString("Failed_to_create_item_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create template.
        /// </summary>
        public static string Failed_to_create_template {
            get {
                return ResourceManager.GetString("Failed_to_create_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Nupkg file.
        /// </summary>
        public static string Failed_to_create_the_Nupkg_file {
            get {
                return ResourceManager.GetString("Failed_to_create_the_Nupkg_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize item.
        /// </summary>
        public static string Failed_to_deserialize_item {
            get {
                return ResourceManager.GetString("Failed_to_deserialize_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load assembly: {0}: {1}.
        /// </summary>
        public static string Failed_to_load_assembly___0____1_ {
            get {
                return ResourceManager.GetString("Failed_to_load_assembly___0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse Id..
        /// </summary>
        public static string Failed_to_parse_Id_ {
            get {
                return ResourceManager.GetString("Failed_to_parse_Id_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload media.
        /// </summary>
        public static string Failed_to_upload_media {
            get {
                return ResourceManager.GetString("Failed_to_upload_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is already defined.
        /// </summary>
        public static string Field_is_already_defined {
            get {
                return ResourceManager.GetString("Field_is_already_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is being assigned two different values.
        /// </summary>
        public static string Field_is_being_assigned_two_different_values {
            get {
                return ResourceManager.GetString("Field_is_being_assigned_two_different_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not defined in the template.
        /// </summary>
        public static string Field_is_not_defined_in_the_template {
            get {
                return ResourceManager.GetString("Field_is_not_defined_in_the_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name expected.
        /// </summary>
        public static string Field_name_expected {
            get {
                return ResourceManager.GetString("Field_name_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path must start with &apos;~&apos;.
        /// </summary>
        public static string File_path_must_start_with____ {
            get {
                return ResourceManager.GetString("File_path_must_start_with____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format not found.
        /// </summary>
        public static string Format_not_found {
            get {
                return ResourceManager.GetString("Format_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found: .
        /// </summary>
        public static string Found__ {
            get {
                return ResourceManager.GetString("Found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating code.
        /// </summary>
        public static string Generating_code {
            get {
                return ResourceManager.GetString("Generating_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating code....
        /// </summary>
        public static string Generating_code___ {
            get {
                return ResourceManager.GetString("Generating_code___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating unit tests....
        /// </summary>
        public static string Generating_unit_tests___ {
            get {
                return ResourceManager.GetString("Generating_unit_tests___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go get a cup of coffee or read some emails - this may take a while....
        /// </summary>
        public static string Go_get_a_cup_of_coffee_or_read_some_emails___this_may_take_a_while___ {
            get {
                return ResourceManager.GetString("Go_get_a_cup_of_coffee_or_read_some_emails___this_may_take_a_while___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey - you haven&apos;t changed the the &apos;project-unique-id&apos;, &apos;wwwroot&apos; or &apos;hostname&apos; in the configuration file..
        /// </summary>
        public static string Hey___you_haven_t_changed_the_the__project_unique_id____wwwroot__or__hostname__in_the___0___configuration_file_ {
            get {
                return ResourceManager.GetString("Hey___you_haven_t_changed_the_the__project_unique_id____wwwroot__or__hostname__in" +
                        "_the___0___configuration_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, GruntJS has not yet been installed. Run the install-grunt.cmd file to install it..
        /// </summary>
        public static string Hey__GruntJS_has_not_yet_been_installed__Run_the_install_grunt_cmd_file_to_install_it_ {
            get {
                return ResourceManager.GetString("Hey__GruntJS_has_not_yet_been_installed__Run_the_install_grunt_cmd_file_to_instal" +
                        "l_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there..
        /// </summary>
        public static string Hi_there_ {
            get {
                return ResourceManager.GetString("Hi_there_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host not found.
        /// </summary>
        public static string Host_not_found {
            get {
                return ResourceManager.GetString("Host_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image reference not found.
        /// </summary>
        public static string Image_reference_not_found {
            get {
                return ResourceManager.GetString("Image_reference_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing website....
        /// </summary>
        public static string Importing_website___ {
            get {
                return ResourceManager.GetString("Importing_website___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental build started....
        /// </summary>
        public static string Incremental_build_started___ {
            get {
                return ResourceManager.GetString("Incremental_build_started___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not valid: .
        /// </summary>
        public static string Input_is_not_valid__ {
            get {
                return ResourceManager.GetString("Input_is_not_valid__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing packages....
        /// </summary>
        public static string Installing___ {
            get {
                return ResourceManager.GetString("Installing___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing project....
        /// </summary>
        public static string Installing_project___ {
            get {
                return ResourceManager.GetString("Installing_project___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not in root-item-path. Skipping..
        /// </summary>
        public static string Item_is_not_in_root_item_path__Skipping_ {
            get {
                return ResourceManager.GetString("Item_is_not_in_root_item_path__Skipping_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        public static string Item_not_found {
            get {
                return ResourceManager.GetString("Item_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item path reference not found.
        /// </summary>
        public static string Item_path_reference_not_found {
            get {
                return ResourceManager.GetString("Item_path_reference_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json file is not valid.
        /// </summary>
        public static string Json_file_is_not_valid {
            get {
                return ResourceManager.GetString("Json_file_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just so you know, I have copied the &apos;Sitecore.Pathfinder.Server.dll&apos; and &apos;NuGet.Core.dll&apos; assemblies to the &apos;/bin&apos; directory in the website and a number of &apos;.aspx&apos; files to the &apos;/sitecore/shell/client/Applications/Pathfinder&apos; directory.
        /// </summary>
        public static string Just_so_you_know__I_have_copied_the__Sitecore_Pathfinder_Server_dll__and__NuGet_Core_dll__assemblies_to_the___bin__directory_in_the_website_and_a_number_of___aspx__files_to_the___sitecore_shell_client_Applications_Pathfinder__directory {
            get {
                return ResourceManager.GetString("Just_so_you_know__I_have_copied_the__Sitecore_Pathfinder_Server_dll__and__NuGet_C" +
                        "ore_dll__assemblies_to_the___bin__directory_in_the_website_and_a_number_of___asp" +
                        "x__files_to_the___sitecore_shell_client_Applications_Pathfinder__directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just so you know, I have updated some files on the website....
        /// </summary>
        public static string Just_so_you_know__I_have_updated_the__Sitecore_Pathfinder_Server_dll__and__NuGet_Core_dll__assemblies_in_the___bin__directory_in_the_website_and_a_number_of___aspx__files_in_the___sitecore_shell_client_Applications_Pathfinder__directory_to_the_latest_version {
            get {
                return ResourceManager.GetString(@"Just_so_you_know__I_have_updated_the__Sitecore_Pathfinder_Server_dll__and__NuGet_Core_dll__assemblies_in_the___bin__directory_in_the_website_and_a_number_of___aspx__files_in_the___sitecore_shell_client_Applications_Pathfinder__directory_to_the_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language not found.
        /// </summary>
        public static string Language_not_found {
            get {
                return ResourceManager.GetString("Language_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout contains errors.
        /// </summary>
        public static string Layout_contains_errors {
            get {
                return ResourceManager.GetString("Layout_contains_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout file is not valid.
        /// </summary>
        public static string Layout_file_is_not_valid {
            get {
                return ResourceManager.GetString("Layout_file_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout is not valid.
        /// </summary>
        public static string Layout_is_not_valid {
            get {
                return ResourceManager.GetString("Layout_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout not found.
        /// </summary>
        public static string Layout_not_found {
            get {
                return ResourceManager.GetString("Layout_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout not found..
        /// </summary>
        public static string Layout_not_found_ {
            get {
                return ResourceManager.GetString("Layout_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout reference not found.
        /// </summary>
        public static string Layout_reference_not_found {
            get {
                return ResourceManager.GetString("Layout_reference_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link field reference not found.
        /// </summary>
        public static string Link_field_reference_not_found {
            get {
                return ResourceManager.GetString("Link_field_reference_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linting items.
        /// </summary>
        public static string Linting_items {
            get {
                return ResourceManager.GetString("Linting_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media item created with wrong ID.
        /// </summary>
        public static string Media_item_created_with_wrong_ID {
            get {
                return ResourceManager.GetString("Media_item_created_with_wrong_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media item not found.
        /// </summary>
        public static string Media_item_not_found {
            get {
                return ResourceManager.GetString("Media_item_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CodeAnalysis.dll is missing. Extensions will not be compiled..
        /// </summary>
        public static string Microsoft_CodeAnalysis_dll_is_missing__Extensions_will_not_be_loaded_ {
            get {
                return ResourceManager.GetString("Microsoft_CodeAnalysis_dll_is_missing__Extensions_will_not_be_loaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing =&gt;.
        /// </summary>
        public static string Missing_Mapping {
            get {
                return ResourceManager.GetString("Missing_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tests were found.
        /// </summary>
        public static string No_tests_were_found {
            get {
                return ResourceManager.GetString("No_tests_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node or Field type expected.
        /// </summary>
        public static string Node_or_Field_type_expected {
            get {
                return ResourceManager.GetString("Node_or_Field_type_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node type expected.
        /// </summary>
        public static string Node_type_expected {
            get {
                return ResourceManager.GetString("Node_type_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string NuGet_file_size {
            get {
                return ResourceManager.GetString("NuGet_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuspec file not found.
        /// </summary>
        public static string Nuspec_file_not_found {
            get {
                return ResourceManager.GetString("Nuspec_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package contains errors and will not be deployed.
        /// </summary>
        public static string Package_contains_errors_and_will_not_be_deployed {
            get {
                return ResourceManager.GetString("Package_contains_errors_and_will_not_be_deployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        public static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing dependency Sitecore packages in Nuget packages....
        /// </summary>
        public static string Packing_dependency_Sitecore_packages_in_Nuget_packages___ {
            get {
                return ResourceManager.GetString("Packing_dependency_Sitecore_packages_in_Nuget_packages___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent name expected.
        /// </summary>
        public static string Parent_name_expected {
            get {
                return ResourceManager.GetString("Parent_name_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tasks to execute..
        /// </summary>
        public static string Pipeline_is_empty__There_are_no_tasks_to_execute_ {
            get {
                return ResourceManager.GetString("Pipeline_is_empty__There_are_no_tasks_to_execute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has not been loaded. Call Load() first.
        /// </summary>
        public static string Project_has_not_been_loaded__Call_Load___first {
            get {
                return ResourceManager.GetString("Project_has_not_been_loaded__Call_Load___first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project item not found: .
        /// </summary>
        public static string Project_item_not_found__ {
            get {
                return ResourceManager.GetString("Project_item_not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Metrics.
        /// </summary>
        public static string Project_Metrics {
            get {
                return ResourceManager.GetString("Project_Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing database....
        /// </summary>
        public static string Publishing___ {
            get {
                return ResourceManager.GetString("Publishing___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding indexes....
        /// </summary>
        public static string Rebuilding_indexes___ {
            get {
                return ResourceManager.GetString("Rebuilding_indexes___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding link database....
        /// </summary>
        public static string Rebuilding_link_database___ {
            get {
                return ResourceManager.GetString("Rebuilding_link_database___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering has not yet been compiled.
        /// </summary>
        public static string Rendering_has_not_yet_been_compiled {
            get {
                return ResourceManager.GetString("Rendering_has_not_yet_been_compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering not found.
        /// </summary>
        public static string Rendering_not_found {
            get {
                return ResourceManager.GetString("Rendering_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering reference not found.
        /// </summary>
        public static string Rendering_reference_not_found {
            get {
                return ResourceManager.GetString("Rendering_reference_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Republishing master database....
        /// </summary>
        public static string Republishing_master_database___ {
            get {
                return ResourceManager.GetString("Republishing_master_database___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting website....
        /// </summary>
        public static string Resetting_website___ {
            get {
                return ResourceManager.GetString("Resetting_website___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running unit tests....
        /// </summary>
        public static string Running_unit_tests___ {
            get {
                return ResourceManager.GetString("Running_unit_tests___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scc.cmd(0,0): information SCC0000: Compiling extensions....
        /// </summary>
        public static string scc_cmd_0_0___information_SCC0000__Compiling_checkers___ {
            get {
                return ResourceManager.GetString("scc_cmd_0_0___information_SCC0000__Compiling_checkers___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse document.
        /// </summary>
        public static string Source_file_is_empty {
            get {
                return ResourceManager.GetString("Source_file_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source files changed.
        /// </summary>
        public static string Source_files_changed {
            get {
                return ResourceManager.GetString("Source_files_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String operator not found.
        /// </summary>
        public static string String_operator_not_found {
            get {
                return ResourceManager.GetString("String_operator_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing project and website....
        /// </summary>
        public static string SynchronizingWebsite {
            get {
                return ResourceManager.GetString("SynchronizingWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Immutable.dll is missing. Extensions will not be compiled..
        /// </summary>
        public static string System_Collections_Immutable_dll_is_missing__Extensions_will_not_be_loaded_ {
            get {
                return ResourceManager.GetString("System_Collections_Immutable_dll_is_missing__Extensions_will_not_be_loaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration file not found.
        /// </summary>
        public static string System_configuration_file_not_found {
            get {
                return ResourceManager.GetString("System_configuration_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T4 item type must include assembly name.
        /// </summary>
        public static string T4_item_type_must_include_assembly_name {
            get {
                return ResourceManager.GetString("T4_item_type_must_include_assembly_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T4 item type not found in the config setting &apos;generate-code:items&apos;.
        /// </summary>
        public static string T4_item_type_not_found_in_the_config_setting__generate_code_items_ {
            get {
                return ResourceManager.GetString("T4_item_type_not_found_in_the_config_setting__generate_code_items_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T4 type name not found in the config setting &apos;generate-code:items&apos;.
        /// </summary>
        public static string T4_type_name_not_found_in_the_config_setting__generate_code_items_ {
            get {
                return ResourceManager.GetString("T4_type_name_not_found_in_the_config_setting__generate_code_items_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found. Skipping.
        /// </summary>
        public static string Task_not_found__Skipping {
            get {
                return ResourceManager.GetString("Task_not_found__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template does not a standard values item.
        /// </summary>
        public static string Template_does_not_a_standard_values_item {
            get {
                return ResourceManager.GetString("Template_does_not_a_standard_values_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template field missing.
        /// </summary>
        public static string Template_field_missing {
            get {
                return ResourceManager.GetString("Template_field_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template missing.
        /// </summary>
        public static string Template_missing {
            get {
                return ResourceManager.GetString("Template_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Runner not found: .
        /// </summary>
        public static string Test_Runner_not_found__ {
            get {
                return ResourceManager.GetString("Test_Runner_not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text document expected.
        /// </summary>
        public static string Text_document_expected {
            get {
                return ResourceManager.GetString("Text_document_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Template&apos; attribute must be specified when &apos;Template.CreateFromFields&apos; equals true..
        /// </summary>
        public static string The__Template__attribute_must_be_specified_when__Template_CreateFromFields__equals_true_ {
            get {
                return ResourceManager.GetString("The__Template__attribute_must_be_specified_when__Template_CreateFromFields__equal" +
                        "s_true_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain valid XML.
        /// </summary>
        public static string The_file_does_not_contain_valid_XML {
            get {
                return ResourceManager.GetString("The_file_does_not_contain_valid_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an error.
        /// </summary>
        public static string The_server_returned_an_error {
            get {
                return ResourceManager.GetString("The_server_returned_an_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey - there is no &apos;Data&apos; directory under the &apos;wwwroot&apos; directory - are you sure = you have set the &apos;wwwroot&apos; correctly in the configuration file.
        /// </summary>
        public static string There_Is_No_Data_Directory {
            get {
                return ResourceManager.GetString("There_Is_No_Data_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey - there is no &apos;Website&apos; directory under the &apos;wwwroot&apos; directory - are you sure = you have set the &apos;wwwroot&apos; correctly in the configuration file.
        /// </summary>
        public static string There_Is_No_Website_Directory {
            get {
                return ResourceManager.GetString("There_Is_No_Website_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting....
        /// </summary>
        public static string Troubleshooting___ {
            get {
                return ResourceManager.GetString("Troubleshooting___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try &quot;scc.cmd list-tasks&quot; for a list of available tasks..
        /// </summary>
        public static string Try__scc_cmd_list_tasks__for_a_list_of_available_tasks_ {
            get {
                return ResourceManager.GetString("Try__scc_cmd_list_tasks__for_a_list_of_available_tasks_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;q&apos; to quit....
        /// </summary>
        public static string Type__q__to_quit___ {
            get {
                return ResourceManager.GetString("Type__q__to_quit___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not found.
        /// </summary>
        public static string Type_not_found {
            get {
                return ResourceManager.GetString("Type_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID clash.
        /// </summary>
        public static string Unique_ID_clash {
            get {
                return ResourceManager.GetString("Unique_ID_clash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating resources....
        /// </summary>
        public static string Updating_resources___ {
            get {
                return ResourceManager.GetString("Updating_resources___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: scc.cmd command [switches].
        /// </summary>
        public static string Usage__scc_cmd_command__switches_ {
            get {
                return ResourceManager.GetString("Usage__scc_cmd_command__switches_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: scc.exe /run [task].
        /// </summary>
        public static string Usage__scc_exe__run__task_ {
            get {
                return ResourceManager.GetString("Usage__scc_exe__run__task_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating website....
        /// </summary>
        public static string Validating_website___ {
            get {
                return ResourceManager.GetString("Validating_website___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is specified in both &apos;Value&apos; attribute and in element. Using value from attribute.
        /// </summary>
        public static string Value_is_specified_in_both__Value__attribute_and_in_element__Using_value_from_attribute {
            get {
                return ResourceManager.GetString("Value_is_specified_in_both__Value__attribute_and_in_element__Using_value_from_att" +
                        "ribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops! scc.exe cannot run in is own directory..
        /// </summary>
        public static string Whoops__scc_exe_cannot_run_in_is_own_directory_ {
            get {
                return ResourceManager.GetString("Whoops__scc_exe_cannot_run_in_is_own_directory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing package exports....
        /// </summary>
        public static string Writing_package_exports___ {
            get {
                return ResourceManager.GetString("Writing_package_exports___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing serialization....
        /// </summary>
        public static string Writing_serialization___ {
            get {
                return ResourceManager.GetString("Writing_serialization___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing website exports....
        /// </summary>
        public static string Writing_website_exports___ {
            get {
                return ResourceManager.GetString("Writing_website_exports___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file is not valid.
        /// </summary>
        public static string XML_file_is_not_valid {
            get {
                return ResourceManager.GetString("XML_file_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specific the --name argument.
        /// </summary>
        public static string You_must_specific_the___name_argument {
            get {
                return ResourceManager.GetString("You_must_specific_the___name_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specific the --to_argument.
        /// </summary>
        public static string You_must_specific_the___to_argument {
            get {
                return ResourceManager.GetString("You_must_specific_the___to_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your configuration file and sample files were missing, so I have created them. You must update the &apos;project-unique-id&apos;, &apos;wwwroot&apos; and &apos;hostname&apos; in the &apos;scconfig.json&apos; configuration file before continuing..
        /// </summary>
        public static string Your_configuration_file_and_sample_files_were_missing__so_I_have_created_them__You_must_update_the__project_unique_id____wwwroot__and__hostname__in_the___0___configuration_file_before_continuing_ {
            get {
                return ResourceManager.GetString("Your_configuration_file_and_sample_files_were_missing__so_I_have_created_them__Yo" +
                        "u_must_update_the__project_unique_id____wwwroot__and__hostname__in_the___0___con" +
                        "figuration_file_before_continuing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project directory was missing, so I have created it. You must update the &apos;project-unique-id&apos;, &apos;wwwroot&apos; and &apos;hostname&apos; in the &apos;scconfig.json&apos; configuration file before continuing..
        /// </summary>
        public static string Your_project_directory_was_missing__so_I_have_created_it__You_must_update_the__project_unique_id____wwwroot__and__hostname__in_the___0___configuration_file_before_continuing_ {
            get {
                return ResourceManager.GetString("Your_project_directory_was_missing__so_I_have_created_it__You_must_update_the__pr" +
                        "oject_unique_id____wwwroot__and__hostname__in_the___0___configuration_file_befor" +
                        "e_continuing_", resourceCulture);
            }
        }
    }
}
