//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Pathfinder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.Pathfinder.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey - there is no &apos;Website&apos; directory under the &apos;wwwroot&apos; directory - are you sure = you have set the &apos;wwwroot&apos; correctly in the configuration file.
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Boolean parameter must have value &quot;True&quot; or &quot;False&quot;.
        /// </summary>
        public static string @__Boolean_parameter_must_have_value__True__or__False_ {
            get {
                return ResourceManager.GetString("__Boolean_parameter_must_have_value__True__or__False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}: Parameter &quot;{0}&quot; is not defined in the parameters template..
        /// </summary>
        public static string _1___Parameter___0___is_not_defined_in_the_parameters_template_ {
            get {
                return ResourceManager.GetString("_1___Parameter___0___is_not_defined_in_the_parameters_template_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}: Placeholder &quot;{0}&quot; is not defined in the parent rendering. Parent rendering has these placeholders: {1}..
        /// </summary>
        public static string _2___Placeholder___0___is_not_defined_in_the_parent_rendering__Parent_rendering_has_these_placeholders___1__ {
            get {
                return ResourceManager.GetString("_2___Placeholder___0___is_not_defined_in_the_parent_rendering__Parent_rendering_h" +
                        "as_these_placeholders___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Component&apos; element expected.
        /// </summary>
        public static string _Component__element_expected {
            get {
                return ResourceManager.GetString("_Component__element_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Field&apos; element must have a &apos;Name&apos; attribute.
        /// </summary>
        public static string _Field__element_must_have_a__Name__attribute {
            get {
                return ResourceManager.GetString("_Field__element_must_have_a__Name__attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Item&apos; element must have a &apos;Template&apos; or &apos;Template.Create&apos; attribute.
        /// </summary>
        public static string _Item__element_must_have_a__Template__or__Template_Create__attribute {
            get {
                return ResourceManager.GetString("_Item__element_must_have_a__Template__or__Template_Create__attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Section&apos; element must have a &apos;Name&apos; attribute.
        /// </summary>
        public static string _Section__element_must_have_a__Name__attribute {
            get {
                return ResourceManager.GetString("_Section__element_must_have_a__Name__attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;version&apos; attribute must have an integer value.
        /// </summary>
        public static string _version__attribute_must_have_an_integer_value {
            get {
                return ResourceManager.GetString("_version__attribute_must_have_an_integer_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string An_error_occured {
            get {
                return ResourceManager.GetString("An_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Template missing.
        /// </summary>
        public static string Base_Template_missing {
            get {
                return ResourceManager.GetString("Base_Template_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply a layout to a template. The template needs a Standard Values..
        /// </summary>
        public static string Cannot_apply_a_layout_to_a_template__The_template_needs_a_Standard_Values_ {
            get {
                return ResourceManager.GetString("Cannot_apply_a_layout_to_a_template__The_template_needs_a_Standard_Values_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string Checking___ {
            get {
                return ResourceManager.GetString("Checking___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning output directory....
        /// </summary>
        public static string Cleaning_output_directory___ {
            get {
                return ResourceManager.GetString("Cleaning_output_directory___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration failed spectacularly.
        /// </summary>
        public static string Configuration_failed_spectacularly {
            get {
                return ResourceManager.GetString("Configuration_failed_spectacularly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying package to website....
        /// </summary>
        public static string Copying_package_to_website___ {
            get {
                return ResourceManager.GetString("Copying_package_to_website___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create item.
        /// </summary>
        public static string Could_not_create_item {
            get {
                return ResourceManager.GetString("Could_not_create_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create section item.
        /// </summary>
        public static string Could_not_create_section_item {
            get {
                return ResourceManager.GetString("Could_not_create_section_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create template field.
        /// </summary>
        public static string Could_not_create_template_field {
            get {
                return ResourceManager.GetString("Could_not_create_template_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating &apos;layout&apos; directory....
        /// </summary>
        public static string Creating__layout__directory___ {
            get {
                return ResourceManager.GetString("Creating__layout__directory___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Nupkg file....
        /// </summary>
        public static string Creating_Nupkg_file___ {
            get {
                return ResourceManager.GetString("Creating_Nupkg_file___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is &apos;core&apos;. Skipping..
        /// </summary>
        public static string Database_is__core___Skipping_ {
            get {
                return ResourceManager.GetString("Database_is__core___Skipping_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not found.
        /// </summary>
        public static string Database_not_found {
            get {
                return ResourceManager.GetString("Database_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device element is missing &quot;Name&quot; attribute..
        /// </summary>
        public static string Device_element_is_missing__Name__attribute_ {
            get {
                return ResourceManager.GetString("Device_element_is_missing__Name__attribute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices not found in database..
        /// </summary>
        public static string Devices_not_found_in_database_ {
            get {
                return ResourceManager.GetString("Devices_not_found_in_database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is not valid.
        /// </summary>
        public static string Document_is_not_valid {
            get {
                return ResourceManager.GetString("Document_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new template.
        /// </summary>
        public static string Failed_to_add_new_template {
            get {
                return ResourceManager.GetString("Failed_to_add_new_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create item path.
        /// </summary>
        public static string Failed_to_create_item_path {
            get {
                return ResourceManager.GetString("Failed_to_create_item_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create template.
        /// </summary>
        public static string Failed_to_create_template {
            get {
                return ResourceManager.GetString("Failed_to_create_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Nupkg file.
        /// </summary>
        public static string Failed_to_create_the_Nupkg_file {
            get {
                return ResourceManager.GetString("Failed_to_create_the_Nupkg_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize item.
        /// </summary>
        public static string Failed_to_deserialize_item {
            get {
                return ResourceManager.GetString("Failed_to_deserialize_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload media.
        /// </summary>
        public static string Failed_to_upload_media {
            get {
                return ResourceManager.GetString("Failed_to_upload_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is already defined.
        /// </summary>
        public static string Field_is_already_defined {
            get {
                return ResourceManager.GetString("Field_is_already_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not defined in the template.
        /// </summary>
        public static string Field_is_not_defined_in_the_template {
            get {
                return ResourceManager.GetString("Field_is_not_defined_in_the_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found: .
        /// </summary>
        public static string Found__ {
            get {
                return ResourceManager.GetString("Found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating code....
        /// </summary>
        public static string Generating_code___ {
            get {
                return ResourceManager.GetString("Generating_code___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey - you haven&apos;t changed the the &apos;project-unique-id&apos;, &apos;wwwroot&apos; or &apos;hostname&apos; in the &apos;{0}&apos; configuration file..
        /// </summary>
        public static string Hey___you_haven_t_changed_the_the__project_unique_id____wwwroot__or__hostname__in_the___0___configuration_file_ {
            get {
                return ResourceManager.GetString("Hey___you_haven_t_changed_the_the__project_unique_id____wwwroot__or__hostname__in" +
                        "_the___0___configuration_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there..
        /// </summary>
        public static string Hi_there_ {
            get {
                return ResourceManager.GetString("Hi_there_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Installing___ {
            get {
                return ResourceManager.GetString("Installing___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        public static string Item_not_found {
            get {
                return ResourceManager.GetString("Item_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json file is not valid.
        /// </summary>
        public static string Json_file_is_not_valid {
            get {
                return ResourceManager.GetString("Json_file_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just so you know, I have copied the &apos;Sitecore.Pathfinder.Server.dll&apos; and &apos;NuGet.Core.dll&apos; assemblies to the &apos;/bin&apos; directory in the website and a number of &apos;.aspx&apos; files to the &apos;/sitecore/shell/client/Applications/Pathfinder&apos; directory.
        /// </summary>
        public static string Just_so_you_know__I_have_copied_the__Sitecore_Pathfinder_Server_dll__and__NuGet_Core_dll__assemblies_to_the___bin__directory_in_the_website_and_a_number_of___aspx__files_to_the___sitecore_shell_client_Applications_Pathfinder__directory {
            get {
                return ResourceManager.GetString("Just_so_you_know__I_have_copied_the__Sitecore_Pathfinder_Server_dll__and__NuGet_C" +
                        "ore_dll__assemblies_to_the___bin__directory_in_the_website_and_a_number_of___asp" +
                        "x__files_to_the___sitecore_shell_client_Applications_Pathfinder__directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just so you know, I have updated the Pathfinder assemblies in the &apos;/bin&apos; directory in the website and the Pathfinder &apos;.aspx&apos; files in the &apos;/sitecore/shell/client/Applications/Pathfinder&apos; directory to the latest version..
        /// </summary>
        public static string Just_so_you_know__I_have_updated_the__Sitecore_Pathfinder_Server_dll__and__NuGet_Core_dll__assemblies_in_the___bin__directory_in_the_website_and_a_number_of___aspx__files_in_the___sitecore_shell_client_Applications_Pathfinder__directory_to_the_latest_version {
            get {
                return ResourceManager.GetString(@"Just_so_you_know__I_have_updated_the__Sitecore_Pathfinder_Server_dll__and__NuGet_Core_dll__assemblies_in_the___bin__directory_in_the_website_and_a_number_of___aspx__files_in_the___sitecore_shell_client_Applications_Pathfinder__directory_to_the_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language not found.
        /// </summary>
        public static string Language_not_found {
            get {
                return ResourceManager.GetString("Language_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout contains errors.
        /// </summary>
        public static string Layout_contains_errors {
            get {
                return ResourceManager.GetString("Layout_contains_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout file is not valid.
        /// </summary>
        public static string Layout_file_is_not_valid {
            get {
                return ResourceManager.GetString("Layout_file_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout not found..
        /// </summary>
        public static string Layout_not_found_ {
            get {
                return ResourceManager.GetString("Layout_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linting items.
        /// </summary>
        public static string Linting_items {
            get {
                return ResourceManager.GetString("Linting_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media item not found.
        /// </summary>
        public static string Media_item_not_found {
            get {
                return ResourceManager.GetString("Media_item_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet file size.
        /// </summary>
        public static string NuGet_file_size {
            get {
                return ResourceManager.GetString("NuGet_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package contains errors and will not be deployed.
        /// </summary>
        public static string Package_contains_errors_and_will_not_be_deployed {
            get {
                return ResourceManager.GetString("Package_contains_errors_and_will_not_be_deployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline is empty. There are no tasks to execute..
        /// </summary>
        public static string Pipeline_is_empty__There_are_no_tasks_to_execute_ {
            get {
                return ResourceManager.GetString("Pipeline_is_empty__There_are_no_tasks_to_execute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has not been loaded. Call Load() first.
        /// </summary>
        public static string Project_has_not_been_loaded__Call_Load___first {
            get {
                return ResourceManager.GetString("Project_has_not_been_loaded__Call_Load___first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project item not found: .
        /// </summary>
        public static string Project_item_not_found__ {
            get {
                return ResourceManager.GetString("Project_item_not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing....
        /// </summary>
        public static string Publishing___ {
            get {
                return ResourceManager.GetString("Publishing___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scc.cmd(0,0): information SCC0000: Compiling checkers....
        /// </summary>
        public static string scc_cmd_0_0___information_SCC0000__Compiling_checkers___ {
            get {
                return ResourceManager.GetString("scc_cmd_0_0___information_SCC0000__Compiling_checkers___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file is empty.
        /// </summary>
        public static string Source_file_is_empty {
            get {
                return ResourceManager.GetString("Source_file_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading resources....
        /// </summary>
        public static string SynchronizingWebsite {
            get {
                return ResourceManager.GetString("SynchronizingWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration file not found.
        /// </summary>
        public static string System_configuration_file_not_found {
            get {
                return ResourceManager.GetString("System_configuration_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found. Skipping.
        /// </summary>
        public static string Task_not_found__Skipping {
            get {
                return ResourceManager.GetString("Task_not_found__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template missing.
        /// </summary>
        public static string Template_missing {
            get {
                return ResourceManager.GetString("Template_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text document expected.
        /// </summary>
        public static string Text_document_expected {
            get {
                return ResourceManager.GetString("Text_document_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain valid XML.
        /// </summary>
        public static string The_file_does_not_contain_valid_XML {
            get {
                return ResourceManager.GetString("The_file_does_not_contain_valid_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an error.
        /// </summary>
        public static string The_server_returned_an_error {
            get {
                return ResourceManager.GetString("The_server_returned_an_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey - there is no &apos;Data&apos; directory under the &apos;wwwroot&apos; directory - are you sure = you have set the &apos;wwwroot&apos; correctly in the configuration file.
        /// </summary>
        public static string There_Is_No_Data_Directory {
            get {
                return ResourceManager.GetString("There_Is_No_Data_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey - there is no &apos;Website&apos; directory under the &apos;wwwroot&apos; directory - are you sure = you have set the &apos;wwwroot&apos; correctly in the configuration file.
        /// </summary>
        public static string There_Is_No_Website_Directory {
            get {
                return ResourceManager.GetString("There_Is_No_Website_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try &quot;scc.cmd list-tasks&quot; for a list of available tasks..
        /// </summary>
        public static string Try__scc_cmd_list_tasks__for_a_list_of_available_tasks_ {
            get {
                return ResourceManager.GetString("Try__scc_cmd_list_tasks__for_a_list_of_available_tasks_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not found.
        /// </summary>
        public static string Type_not_found {
            get {
                return ResourceManager.GetString("Type_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID clash.
        /// </summary>
        public static string Unique_ID_clash {
            get {
                return ResourceManager.GetString("Unique_ID_clash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating resources....
        /// </summary>
        public static string Updating_resources___ {
            get {
                return ResourceManager.GetString("Updating_resources___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: scc.cmd command [switches].
        /// </summary>
        public static string Usage__scc_cmd_command__switches_ {
            get {
                return ResourceManager.GetString("Usage__scc_cmd_command__switches_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: scc.exe /run [task].
        /// </summary>
        public static string Usage__scc_exe__run__task_ {
            get {
                return ResourceManager.GetString("Usage__scc_exe__run__task_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is specified in both &apos;Value&apos; attribute and in element. Using value from attribute.
        /// </summary>
        public static string Value_is_specified_in_both__Value__attribute_and_in_element__Using_value_from_attribute {
            get {
                return ResourceManager.GetString("Value_is_specified_in_both__Value__attribute_and_in_element__Using_value_from_att" +
                        "ribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file is not valid.
        /// </summary>
        public static string XML_file_is_not_valid {
            get {
                return ResourceManager.GetString("XML_file_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specific the --name argument.
        /// </summary>
        public static string You_must_specific_the___name_argument {
            get {
                return ResourceManager.GetString("You_must_specific_the___name_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specific the --to_argument.
        /// </summary>
        public static string You_must_specific_the___to_argument {
            get {
                return ResourceManager.GetString("You_must_specific_the___to_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your configuration file and sample files were missing, so I have created them. You must update the &apos;project-unique-id&apos;, &apos;wwwroot&apos; and &apos;hostname&apos; in the &apos;scconfig.json&apos; configuration file before continuing..
        /// </summary>
        public static string Your_configuration_file_and_sample_files_were_missing__so_I_have_created_them__You_must_update_the__project_unique_id____wwwroot__and__hostname__in_the___0___configuration_file_before_continuing_ {
            get {
                return ResourceManager.GetString("Your_configuration_file_and_sample_files_were_missing__so_I_have_created_them__Yo" +
                        "u_must_update_the__project_unique_id____wwwroot__and__hostname__in_the___0___con" +
                        "figuration_file_before_continuing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project directory was missing, so I have created it. You must update the &apos;project-unique-id&apos;, &apos;wwwroot&apos; and &apos;hostname&apos; in the &apos;scconfig.json&apos; configuration file before continuing..
        /// </summary>
        public static string Your_project_directory_was_missing__so_I_have_created_it__You_must_update_the__project_unique_id____wwwroot__and__hostname__in_the___0___configuration_file_before_continuing_ {
            get {
                return ResourceManager.GetString("Your_project_directory_was_missing__so_I_have_created_it__You_must_update_the__pr" +
                        "oject_unique_id____wwwroot__and__hostname__in_the___0___configuration_file_befor" +
                        "e_continuing_", resourceCulture);
            }
        }
    }
}
