//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Pathfinder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.Pathfinder.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Field&apos; element must have a &apos;Name&apos; attribute.
        /// </summary>
        public static string _Field__element_must_have_a__Name__attribute {
            get {
                return ResourceManager.GetString("_Field__element_must_have_a__Name__attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string An_error_occured {
            get {
                return ResourceManager.GetString("An_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply a layout to a template. The template needs a Standard Values..
        /// </summary>
        public static string Cannot_apply_a_layout_to_a_template__The_template_needs_a_Standard_Values_ {
            get {
                return ResourceManager.GetString("Cannot_apply_a_layout_to_a_template__The_template_needs_a_Standard_Values_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string Checking___ {
            get {
                return ResourceManager.GetString("Checking___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout contains errors.
        /// </summary>
        public static string Layout_contains_errors {
            get {
                return ResourceManager.GetString("Layout_contains_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout file is not valid.
        /// </summary>
        public static string Layout_file_is_not_valid {
            get {
                return ResourceManager.GetString("Layout_file_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout not found..
        /// </summary>
        public static string Layout_not_found_ {
            get {
                return ResourceManager.GetString("Layout_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linting items.
        /// </summary>
        public static string Linting_items {
            get {
                return ResourceManager.GetString("Linting_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline is empty. There are no tasks to execute..
        /// </summary>
        public static string Pipeline_is_empty__There_are_no_tasks_to_execute_ {
            get {
                return ResourceManager.GetString("Pipeline_is_empty__There_are_no_tasks_to_execute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found. Skipping.
        /// </summary>
        public static string Task_not_found__Skipping {
            get {
                return ResourceManager.GetString("Task_not_found__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: scc.exe /run [task].
        /// </summary>
        public static string Usage__scc_exe__run__task_ {
            get {
                return ResourceManager.GetString("Usage__scc_exe__run__task_", resourceCulture);
            }
        }
    }
}
