//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using Sitecore.Pathfinder.Diagnostics;

namespace Sitecore.Pathfinder.Configuration
{
    #region Designer generated code

    public partial interface IFactory
    {
        [NotNull]
        Sitecore.Pathfinder.Languages.BinFiles.BinFile BinFile([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project, [NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string filePath);

        [NotNull]
        Sitecore.Pathfinder.Tasks.Building.IBuildContext BuildContext();

        [NotNull]
        Sitecore.Pathfinder.Checking.ICheckerContext CheckerContext([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project);

        [NotNull]
        Sitecore.Pathfinder.Compiling.Compilers.ICompileContext CompileContext([NotNull] Sitecore.Pathfinder.Projects.IProject project);

        [NotNull]
        Sitecore.Pathfinder.Languages.ConfigFiles.ConfigFile ConfigFile([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project, [NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string filePath);

        [NotNull]
        Sitecore.Pathfinder.Languages.Content.ContentFile ContentFile([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project, [NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string filePath);

        [NotNull]
        Sitecore.Pathfinder.Projects.IDatabase Database([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project, [NotNull] string databaseName, [NotNull] System.Collections.Generic.IEnumerable<string> languageNames);

        [NotNull]
        Sitecore.Pathfinder.Projects.References.DeviceReference DeviceReference([NotNull] Sitecore.Pathfinder.Projects.IProjectItem owner, [NotNull] Sitecore.Pathfinder.Projects.SourceProperty<string> sourceProperty, [NotNull] string referenceText, [NotNull] string databaseName);

        [NotNull]
        Sitecore.Pathfinder.Projects.IDiagnostic Diagnostic(int msg, [NotNull] string fileName, Sitecore.Pathfinder.Snapshots.TextSpan span, Sitecore.Pathfinder.Diagnostics.Severity severity, [NotNull] string text);

        [NotNull]
        Sitecore.Pathfinder.ProjectTrees.DirectoryProjectTreeItem DirectoryProjectTreeItem([NotNull] Sitecore.Pathfinder.ProjectTrees.IProjectTree projectTree, [NotNull] string directory);

        [NotNull]
        Sitecore.Pathfinder.Emitting.IEmitContext EmitContext([NotNull] Sitecore.Pathfinder.Emitting.IProjectEmitter projectEmitter, [NotNull] Sitecore.Pathfinder.Projects.IProjectBase project);

        [NotNull]
        Sitecore.Pathfinder.Projects.Items.Field Field([NotNull] Sitecore.Pathfinder.Projects.Items.Item item);

        [NotNull]
        Sitecore.Pathfinder.Compiling.FieldCompilers.IFieldCompileContext FieldCompileContext();

        [NotNull]
        Sitecore.Pathfinder.Projects.Files.File File([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project, [NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string filePath);

        [NotNull]
        Sitecore.Pathfinder.ProjectTrees.FileProjectTreeItem FileProjectTreeItem([NotNull] Sitecore.Pathfinder.ProjectTrees.IProjectTree projectTree, [NotNull] string fileName);

        [NotNull]
        Sitecore.Pathfinder.Projects.References.FileReference FileReference([NotNull] Sitecore.Pathfinder.Projects.IProjectItem owner, [NotNull] Sitecore.Pathfinder.Projects.SourceProperty<string> sourceProperty, [NotNull] string referenceText);

        [NotNull]
        Sitecore.Pathfinder.Projects.References.FileReference FileReference([NotNull] Sitecore.Pathfinder.Projects.IProjectItem owner, [NotNull] Sitecore.Pathfinder.Snapshots.ITextNode textNode, [NotNull] string referenceText);

        [NotNull]
        Sitecore.Pathfinder.Projects.Items.Item Item([NotNull] Sitecore.Pathfinder.Projects.IDatabase database, System.Guid guid, [NotNull] string itemName, [NotNull] string itemIdOrPath, [NotNull] string templateIdOrPath);

        [NotNull]
        Sitecore.Pathfinder.Parsing.Items.ItemParseContext ItemParseContext([NotNull] Sitecore.Pathfinder.Parsing.IParseContext parseContext, [NotNull] Sitecore.Pathfinder.Parsing.Items.ItemParser parser, [NotNull] Sitecore.Pathfinder.Projects.IDatabase database, [NotNull] string parentItemPath, bool isImport);

        [NotNull]
        Sitecore.Pathfinder.Languages.Json.JsonTextSnapshot JsonTextSnapshot([NotNull] Sitecore.Pathfinder.Snapshots.ISourceFile sourceFile, [NotNull] string contents);

        [NotNull]
        Sitecore.Pathfinder.Projects.Items.Language Language([NotNull] string languageName);

        [NotNull]
        Sitecore.Pathfinder.Compiling.FieldCompilers.LayoutCompileContext LayoutCompileContext([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project, [NotNull] Sitecore.Pathfinder.Projects.IDatabase database, [NotNull] Sitecore.Pathfinder.Snapshots.ITextSnapshot snapshot);

        [NotNull]
        Sitecore.Pathfinder.Compiling.FieldCompilers.LayoutCompiler LayoutCompiler();

        [NotNull]
        Sitecore.Pathfinder.Projects.References.LayoutReference LayoutReference([NotNull] Sitecore.Pathfinder.Projects.IProjectItem owner, [NotNull] Sitecore.Pathfinder.Projects.SourceProperty<string> sourceProperty, [NotNull] string referenceText, [NotNull] string databaseName);

        [NotNull]
        Sitecore.Pathfinder.Projects.References.LayoutRenderingReference LayoutRenderingReference([NotNull] Sitecore.Pathfinder.Projects.IProjectItem owner, [NotNull] Sitecore.Pathfinder.Projects.SourceProperty<string> sourceProperty, [NotNull] string referenceText, [NotNull] string databaseName);

        [NotNull]
        Sitecore.Pathfinder.Languages.Media.MediaFile MediaFile([NotNull] Sitecore.Pathfinder.Projects.IDatabase database, [NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string itemName, [NotNull] string itemPath, [NotNull] string filePath);

        [NotNull]
        Sitecore.Pathfinder.Tasks.Building.OutputFile OutputFile([NotNull] string fileName);

        [NotNull]
        Sitecore.Pathfinder.Parsing.IParseContext ParseContext([NotNull] Sitecore.Pathfinder.Projects.IProject project, [NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] Sitecore.Pathfinder.Parsing.PathMappingContext pathMappingContext);

        [NotNull]
        Sitecore.Pathfinder.Parsing.PathMappingContext PathMappingContext([NotNull] Sitecore.Pathfinder.IO.IPathMapperService pathMapper);

        [NotNull]
        Sitecore.Pathfinder.IO.IPathMatcher PathMatcher([NotNull] string include, [NotNull] string exclude);

        [NotNull]
        Sitecore.Pathfinder.Projects.IProject Project([NotNull] Sitecore.Pathfinder.Projects.ProjectOptions projectOptions, [NotNull] System.Collections.Generic.IEnumerable<string> sourceFileNames);

        [NotNull]
        Sitecore.Pathfinder.Projects.ProjectContext ProjectContext();

        [NotNull]
        Sitecore.Pathfinder.Projects.ProjectImportsService ProjectImportsService();

        [NotNull]
        Sitecore.Pathfinder.Projects.ProjectIndexes.ProjectIndexes ProjectIndexes([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project);

        [NotNull]
        Sitecore.Pathfinder.Projects.ProjectOptions ProjectOptions([NotNull] string databaseName);

        [NotNull]
        Sitecore.Pathfinder.Projects.IProjectService ProjectService();

        [NotNull]
        Sitecore.Pathfinder.ProjectTrees.IProjectTree ProjectTree([NotNull] string toolsDirectory, [NotNull] string projectDirectory);

        [NotNull]
        Sitecore.Pathfinder.ProjectTrees.ProjectTreeVisitor ProjectTreeVisitor();

        [NotNull]
        Sitecore.Pathfinder.Projects.References.Reference Reference([NotNull] Sitecore.Pathfinder.Projects.IProjectItem owner, [NotNull] Sitecore.Pathfinder.Projects.SourceProperty<string> sourceProperty, [NotNull] string referenceText, [NotNull] string databaseName);

        [NotNull]
        Sitecore.Pathfinder.Projects.References.Reference Reference([NotNull] Sitecore.Pathfinder.Projects.IProjectItem owner, [NotNull] Sitecore.Pathfinder.Snapshots.ITextNode textNode, [NotNull] string referenceText, [NotNull] string databaseName);

        [NotNull]
        Sitecore.Pathfinder.Languages.Renderings.Rendering Rendering([NotNull] Sitecore.Pathfinder.Projects.IDatabase database, [NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string itemPath, [NotNull] string itemName, [NotNull] string filePath, [NotNull] string templateIdOrPath);

        [NotNull]
        Sitecore.Pathfinder.Languages.Serialization.SerializationFile SerializationFile([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project, [NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string filePath);

        [NotNull]
        Sitecore.Pathfinder.Snapshots.ISnapshot SerializationTextSnapshot([NotNull] Sitecore.Pathfinder.Snapshots.ISourceFile sourceFile);

        [NotNull]
        Sitecore.Pathfinder.Snapshots.ISnapshot Snapshot([NotNull] Sitecore.Pathfinder.Snapshots.ISourceFile sourceFile);

        [NotNull]
        Sitecore.Pathfinder.Snapshots.SnapshotParseContext SnapshotParseContext([NotNull] Sitecore.Pathfinder.Projects.IProjectBase project, [NotNull] System.Collections.Generic.IDictionary<string, string> tokens);

        [NotNull]
        Sitecore.Pathfinder.Snapshots.SnapshotTextNode SnapshotTextNode([NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot);

        [NotNull]
        Sitecore.Pathfinder.Snapshots.SourceFile SourceFile([NotNull] string absoluteFileName);

        [NotNull]
        Sitecore.Pathfinder.Projects.Templates.Template Template([NotNull] Sitecore.Pathfinder.Projects.IDatabase database, System.Guid guid, [NotNull] string itemName, [NotNull] string itemIdOrPath);

        [NotNull]
        Sitecore.Pathfinder.Projects.Templates.TemplateField TemplateField([NotNull] Sitecore.Pathfinder.Projects.Templates.Template template, System.Guid guid);

        [NotNull]
        Sitecore.Pathfinder.Projects.Templates.TemplateSection TemplateSection([NotNull] Sitecore.Pathfinder.Projects.Templates.Template template, System.Guid guid);

        [NotNull]
        Sitecore.Pathfinder.Snapshots.TextNode TextNode([NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string key, [NotNull] string value, Sitecore.Pathfinder.Snapshots.TextSpan textSpan);

        [NotNull]
        Sitecore.Pathfinder.Snapshots.TextNode TextNode([NotNull] Sitecore.Pathfinder.Snapshots.ISnapshot snapshot, [NotNull] string key, [NotNull] string value, Sitecore.Pathfinder.Snapshots.TextSpan textSpan, [NotNull] System.Collections.Generic.IEnumerable<Sitecore.Pathfinder.Snapshots.ITextNode> attributes, [NotNull] System.Collections.Generic.IEnumerable<Sitecore.Pathfinder.Snapshots.ITextNode> childNodes);

        [NotNull]
        Sitecore.Pathfinder.Projects.Items.Version Version(int number);

        [NotNull]
        Sitecore.Pathfinder.Languages.Xml.XmlTextSnapshot XmlTextSnapshot([NotNull] Sitecore.Pathfinder.Snapshots.ISourceFile sourceFile, [NotNull] string contents, [NotNull] string schemaNamespace, [NotNull] string schemaFileName);

        [NotNull]
        Sitecore.Pathfinder.Languages.Yaml.YamlTextSnapshot YamlTextSnapshot([NotNull] Sitecore.Pathfinder.Snapshots.ISourceFile sourceFile, [NotNull] string contents);

    }

    #endregion
}

#pragma warning restore 1591
