
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using Sitecore.Data.Items;
using Sitecore.Diagnostics;

namespace sitecore.templates.Sample
{
  #region Designer generated code

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
  public partial class HelloWorld
  {
    public HelloWorld(Item innerItem)
    {
      this.InnerItem = innerItem;
    }

    [NotNull] 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
    public Item InnerItem { get; private set; }

    [NotNull]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
    public string Text { get { return this.InnerItem["Text"]; } }

    [NotNull]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
    public string Title { get { return this.InnerItem["Title"]; } }

    [NotNull]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
    public string Image { get { return this.InnerItem["Image"]; } }

    [NotNull]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
    public string Flips { get { return this.InnerItem["Flips"]; } }

    [NotNull]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
    public string ___Workflow { get { return this.InnerItem["__Workflow"]; } }

    [NotNull]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
    public string ___WorkflowState { get { return this.InnerItem["__Workflow State"]; } }
  }

  #endregion
}

#pragma warning restore 1591
