//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using Sitecore;
using Sitecore.Data.Items;

namespace Sitecore.Templates.CleanBlog
{
    #region Designer generated code

    [System.Diagnostics.DebuggerStepThrough()]
    [System.CodeDom.Compiler.GeneratedCode("Sitecore.Pathfinder", "1.0.0.0")]
    public partial class Post
    {
        public Post(Item innerItem)
        {
          InnerItem = innerItem;
        }

        [NotNull]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore.Pathfinder", "1.0.0.0")]
        public Item InnerItem { get; private set; }

        [NotNull]
        [System.CodeDom.Compiler.GeneratedCode("Sitecore.Pathfinder", "1.0.0.0")]
        public string Title { get { return InnerItem["Title"]; } }

        [NotNull]
        [System.CodeDom.Compiler.GeneratedCode("Sitecore.Pathfinder", "1.0.0.0")]
        public string Subtitle { get { return InnerItem["Subtitle"]; } }

        [NotNull]
        [System.CodeDom.Compiler.GeneratedCode("Sitecore.Pathfinder", "1.0.0.0")]
        public string Posted { get { return InnerItem["Posted"]; } }

        [NotNull]
        [System.CodeDom.Compiler.GeneratedCode("Sitecore.Pathfinder", "1.0.0.0")]
        public string Text { get { return InnerItem["Text"]; } }

    }

    #endregion
}

#pragma warning restore 1591
